pfUI.addonskinner:RegisterSkin("EQL3", function()

  local penv = pfUI:GetEnvironment()
  local StripTextures, CreateBackdrop, SkinButton, SkinCloseButton, SkinArrowButton, SkinCheckbox, SkinScrollbar, SkinSlider, SetHighlight, SetAllPointsOffset, EnableMovable, hooksecurefunc, HookScript = 
  penv.StripTextures, penv.CreateBackdrop, penv.SkinButton, penv.SkinCloseButton, penv.SkinArrowButton, penv.SkinCheckbox, penv.SkinScrollbar, penv.SkinSlider, penv.SetHighlight, penv.SetAllPointsOffset, penv.EnableMovable, penv.hooksecurefunc, penv.HookScript

  local noop = function() end

  StripTextures(EQL3_Tracker_MinimizeButton)
  CreateBackdrop(EQL3_Tracker_MinimizeButton)
  SetHighlight(EQL3_Tracker_MinimizeButton)
  SetAllPointsOffset(EQL3_Tracker_MinimizeButton.backdrop, EQL3_Tracker_MinimizeButton, 8)
  EQL3_Tracker_MinimizeButton:SetPoint("TOPRIGHT", EQL3_QuestWatchFrame, "TOPRIGHT", 2, -5)
  EQL3_Tracker_MinimizeButton.text = EQL3_Tracker_MinimizeButton:CreateFontString(nil, "OVERLAY")
  EQL3_Tracker_MinimizeButton.text:SetFontObject(GameFontWhite)
  EQL3_Tracker_MinimizeButton.text:SetPoint("CENTER", EQL3_Tracker_MinimizeButton.backdrop, "CENTER", -1, 0)
  EQL3_Tracker_MinimizeButton:SetNormalTexture(nil)
  EQL3_Tracker_MinimizeButton.SetNormalTexture = noop
  EQL3_Tracker_MinimizeButton:SetHighlightTexture(nil)
  EQL3_Tracker_MinimizeButton.SetHighlightTexture = noop
  EQL3_Tracker_MinimizeButton:SetPushedTexture(nil)
  EQL3_Tracker_MinimizeButton.SetPushedTexture = noop
  local collapseStatus = function()
    if EQL3_Player then
      EQL3_Tracker_MinimizeButton.text:SetText(QuestlogOptions[EQL3_Player].TrackerIsMinimized == 0 and "-" or "+")
    end    
  end
  HookScript(EQL3_Tracker_MinimizeButton, "OnShow", function()
    collapseStatus()
  end)
  hooksecurefunc("EQL3_Toggle_Tracker", function()
    collapseStatus()
  end,true)
  StripTextures(EQL3_QuestLogFrame)
  StripTextures(EQL3_QuestLogFrame_Description)
  CreateBackdrop(EQL3_QuestLogFrame, nil, nil, .75)
  EQL3_QuestLogFrame.backdrop:SetPoint("TOPLEFT", EQL3_QuestLogFrame, "TOPLEFT", 0, -3)
  EQL3_QuestLogFrame.backdrop:SetPoint("BOTTOMRIGHT", EQL3_QuestLogFrame, "BOTTOMRIGHT", -30, -3)
  HookScript(EQL3_QuestLogFrame_Description, "OnShow", function()
    EQL3_QuestLogFrame.backdrop:SetPoint("BOTTOMRIGHT", EQL3_QuestLogFrame_Description, "BOTTOMRIGHT", -20, -3)
  end)
  HookScript(EQL3_QuestLogFrame_Description, "OnHide", function()
    EQL3_QuestLogFrame.backdrop:SetPoint("BOTTOMRIGHT", EQL3_QuestLogFrame, "BOTTOMRIGHT", -30, -3)
  end)
  EQL3_QuestLogTitleText:ClearAllPoints()
  EQL3_QuestLogTitleText:SetPoint("TOP", EQL3_QuestLogFrame.backdrop, 0, -5)
  EQL3_QuestLogVersionText:ClearAllPoints()
  EQL3_QuestLogVersionText:SetPoint("TOPRIGHT", EQL3_QuestLogFrame.backdrop, -45, -5)
  EQL3_QuestLogTrack:ClearAllPoints()
  EQL3_QuestLogTrack:SetPoint("TOPLEFT", EQL3_QuestLogFrame.backdrop, 40, -40)
  EQL3_QuestLogQuestCount:ClearAllPoints()
  EQL3_QuestLogQuestCount:SetPoint("TOPRIGHT", EQL3_QuestLogFrame.backdrop, -12, -40)
  EQL3_QuestLogCountRight.SetPoint = noop
  EQL3_QuestLogTitleText.SetPoint = noop
  EQL3_QuestLogVersionText.SetPoint = noop
  SkinCloseButton(EQL3_QuestLogFrameCloseButton, EQL3_QuestLogFrame.backdrop, -6, -6)
  SkinCloseButton(EQL3_QuestLogFrameCloseButton2, EQL3_QuestLogFrame.backdrop, -6, -6)
  SkinArrowButton(EQL3_QuestLogFrameMinimizeButton, "left", 15)
  EQL3_QuestLogFrameMinimizeButton:SetPoint("RIGHT", EQL3_QuestLogFrameCloseButton2, "LEFT", -2, 0)  
  SkinArrowButton(EQL3_QuestLogFrameMaximizeButton, "right", 15)
  EQL3_QuestLogFrameMaximizeButton:SetPoint("RIGHT", EQL3_QuestLogFrameCloseButton, "LEFT", -2, 0)
  SkinButton(EQL3_QuestFrameOptionsButton)
  SkinButton(EQL3_QuestLogFrameAbandonButton)
  SkinButton(EQL3_QuestFramePushQuestButton)
  StripTextures(EQL3_QuestLogListScrollFrame)
  SkinScrollbar(EQL3_QuestLogListScrollFrameScrollBar)
  StripTextures(EQL3_QuestLogDetailScrollFrame)
  SkinScrollbar(EQL3_QuestLogDetailScrollFrameScrollBar, true)
  StripTextures(EQL3_QuestLogFrame_Details)
  EQL3_QuestLogDetailScrollFrame.bg = EQL3_QuestLogDetailScrollFrame:CreateTexture(nil, "BACKGROUND")
  EQL3_QuestLogDetailScrollFrame.bg:SetTexture([[Interface\Stationery\StationeryTest1]])
  EQL3_QuestLogDetailScrollFrame.bg:SetAllPoints()

  -- organizer popup
  StripTextures(EQL3_OrganizeFrame)
  CreateBackdrop(EQL3_OrganizeFrame, nil, nil, .75)
  StripTextures(EQL3_OrganizeFrame_Text, true, "BACKGROUND")
  CreateBackdrop(EQL3_OrganizeFrame_Text, nil, true)
  SkinButton(EQL3_OrganizeFrame_Okay)
  SkinButton(EQL3_OrganizeFrame_Cancel)
  EnableMovable(EQL3_OrganizeFrame)

  -- options
  CreateBackdrop(EQL3_OptionsFrame_Header_Log, nil, nil, .9)
  SetAllPointsOffset(EQL3_OptionsFrame_Header_Log.backdrop, EQL3_OptionsFrame_Header_Log, 3)
  CreateBackdrop(EQL3_OptionsFrame_Header_Color, nil, nil, .9)
  SetAllPointsOffset(EQL3_OptionsFrame_Header_Color.backdrop, EQL3_OptionsFrame_Header_Color, 3)
  CreateBackdrop(EQL3_OptionsFrame_Header_Tracker, nil, nil, .9)
  SetAllPointsOffset(EQL3_OptionsFrame_Header_Tracker.backdrop, EQL3_OptionsFrame_Header_Tracker, 3)
  CreateBackdrop(EQL3_OptionsFrame_Header_Tooltip, nil, nil, .9)
  SetAllPointsOffset(EQL3_OptionsFrame_Header_Tooltip.backdrop, EQL3_OptionsFrame_Header_Tooltip, 3)
  StripTextures(EQL3_OptionsFrame)
  CreateBackdrop(EQL3_OptionsFrame, nil, nil, .75)
  SkinCloseButton(EQL3_OptionsFrameCloseButton, EQL3_OptionsFrame.backdrop, -6, -6)
  SkinArrowButton(EQL3_OptionsFrameLoadButton, "down", 15)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_ShowQuestLevels,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_QuestLevelsOnlyInLog,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_RestoreUponSelect,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_MinimizeUponClose,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_AutoCompleteQuests,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_InfoOnQuestComplete,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_LockQuestLog,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_CustomZoneColor,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_CustomHeaderColor,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_FadeHeaderColor,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_CustomObjectiveColor,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_FadeObjectiveColor,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_CustomTrackerBGColor,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_CustomTooltipInfoColor,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_ShowObjectiveMarkers,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_UseTrackerListing,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_List1,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_List2,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_List3,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_List4,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_Symbol1,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_Symbol2,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_Symbol3,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_Symbol4,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_ShowZones,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_SortTracker,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_LockTracker,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_AddNew,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_RemoveFinished,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_MinimizeFinished,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_HideCompletedObjectives,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_AddUntracked,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_ShowMinimizer,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_ShowItemTooltip,20)
  SkinCheckbox(EQL3_OptionsFrame_Checkbox_ShowMobTooltip,20)
  SkinButton(EQL3_OptionsFrame_Button_QuestLog)
  SkinButton(EQL3_OptionsFrame_Button_RestoreColors)
  SkinButton(EQL3_OptionsFrame_Button_RestoreTracker)
  SkinSlider(EQL3_OptionsFrame_Slider_LogOpacity)
  SkinSlider(EQL3_OptionsFrame_Slider_TrackerFontSize)
  
  pfUI.addonskinner:UnregisterSkin("EQL3")
end)